// <auto-generated />
using System;
using System.Collections.Generic;
using CadabraTest.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CadabraTest.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125211322_AddAnalysisTable")]
    partial class AddAnalysisTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CadabraTest.API.Models.AnalysisResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("CadabraTest.API.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CadabraTest.API.Models.AnalysisResponse", b =>
                {
                    b.OwnsOne("CadabraTest.API.Models.AIAnalysis", "AIAnalysis", b1 =>
                        {
                            b1.Property<Guid>("AnalysisResponseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Insights")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<List<string>>("Recommendations")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnalysisResponseId");

                            b1.ToTable("Analyses");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisResponseId");
                        });

                    b.OwnsOne("CadabraTest.API.Models.PartMetadata", "PartMetadata", b1 =>
                        {
                            b1.Property<Guid>("AnalysisResponseId")
                                .HasColumnType("uuid");

                            b1.Property<Dictionary<string, string>>("CustomProperties")
                                .HasColumnType("hstore");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double?>("Mass")
                                .HasColumnType("double precision");

                            b1.Property<string>("Material")
                                .HasColumnType("text");

                            b1.Property<string>("PartName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double?>("Volume")
                                .HasColumnType("double precision");

                            b1.HasKey("AnalysisResponseId");

                            b1.ToTable("Analyses");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisResponseId");

                            b1.OwnsOne("CadabraTest.API.Models.Dimensions", "Dimensions", b2 =>
                                {
                                    b2.Property<Guid>("PartMetadataAnalysisResponseId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Height")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Length")
                                        .HasColumnType("double precision");

                                    b2.Property<string>("Units")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<double>("Width")
                                        .HasColumnType("double precision");

                                    b2.HasKey("PartMetadataAnalysisResponseId");

                                    b2.ToTable("Analyses");

                                    b2.WithOwner()
                                        .HasForeignKey("PartMetadataAnalysisResponseId");
                                });

                            b1.Navigation("Dimensions");
                        });

                    b.Navigation("AIAnalysis");

                    b.Navigation("PartMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
